services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - appnet

  web:
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
    networks:
      - appnet

  mobile:
    build: ./mobile
    ports:
      - "8081:8081"
    volumes:
      - ./mobile:/app
      - /app/node_modules
    networks:
      - appnet
networks:
  appnet:
